# Generated by Django 4.2.7 on 2024-02-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='realform',
            old_name='Purpose',
            new_name='purpose',
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.RemoveField(
            model_name='realform',
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='realform',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='realform',
            name='Material',
        ),
        migrations.AddField(
            model_name='material',
            name='debit_notebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='exam_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='pen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realform',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegestore.course'),
        ),
        migrations.AddField(
            model_name='realform',
            name='debit_notebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realform',
            name='exam_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realform',
            name='pen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realform',
            name='AGE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='realform',
            name='EMAIL',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='realform',
            name='PHONE_NUMBER',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='realform',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegestore.department'),
        ),
    ]
