# Generated by Django 4.2.7 on 2024-02-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegestore', '0002_rename_courses_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realform',
            name='PHONE_NUMBER',
            field=models.CharField(max_length=12),
        ),
    ]
